######################################################################
# Automatically generated by qmake (1.07a) Tue Jun 19 07:53:37 2007
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += MIFit


