#ifndef MI_CORELIB_H
#define MI_CORELIB_H

#include "Annotation.h"
#include "ATOMLABEL.h"
#include "Cfiles.h"
#include "CHIRALDICT.h"
#include "clusterList.h"
#include "Colors.h"
#include "ColorUtil.h"
#include "CONTACT.h"
#include "corelib.h"
#include "CRect.h"
#include "Helix.h"
#include "GeomRefiner.h"
#include "MouseFlags.h"
#include "MIConfig.h"
#include "MIData.h"
#include "mifit_algorithm.h"
#include "Molecule.h"
#include "MoleculeType.h"
#include "RenderStyle.h"
#include "RESIDUE.h"
#include "RibbonSegment.h"
#include "RibbonSpan.h"
#include "rotlsq.h"
#include "SecondaryStructure.h"
#include "seqtypes.h"
#include "Stack.h"
#include "SurfaceSphere.h"
#include "SURFDOT.h"
#include "Version.h"
#include "ViewPoint.h"
#include "xmlarchive.h"

#endif // ifndef MI_CORELIB_H
